"""Initial baseline

Revision ID: c3f9eb5a49d2
Revises: 
Create Date: 2026-02-23 23:39:46.562986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f9eb5a49d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_energy_drinks')
    with op.batch_alter_table('energy_drinks', schema=None) as batch_op:
        batch_op.alter_column('is_plantation',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('fertilizers', schema=None) as batch_op:
        batch_op.alter_column('effect_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('group_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_chats_auto_delete_enabled'), ['auto_delete_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_chats_notify_disabled'), ['notify_disabled'], unique=False)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index('idx_inventory_drink', ['drink_id'], unique=False)
        batch_op.create_index('idx_inventory_player', ['player_id'], unique=False)
        batch_op.create_index('idx_inventory_rarity', ['rarity'], unique=False)

    with op.batch_alter_table('plantation_beds', schema=None) as batch_op:
        batch_op.alter_column('status_effect',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'fertilizers', ['fertilizer_id'], ['id'])

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'ru'"))
        batch_op.alter_column('remind',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('auto_search_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('farmer_auto_water',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('farmer_auto_harvest',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('farmer_auto_plant',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('farmer_auto_fertilize',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('farmer_fert_priority',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('farmer_silent',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('farmer_summary_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('farmer_seed_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'any'"))
        batch_op.alter_column('farmer_seed_ids',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('farmer_seed_priority',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('farmer_session_stats',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('casino_achievements',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('scheduled_auto_deletes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_auto_deletes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('casino_achievements',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('farmer_session_stats',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('farmer_seed_priority',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('farmer_seed_ids',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('farmer_seed_mode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'any'"))
        batch_op.alter_column('farmer_summary_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('farmer_silent',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('farmer_fert_priority',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('farmer_auto_fertilize',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('farmer_auto_plant',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('farmer_auto_harvest',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('farmer_auto_water',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('auto_search_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('remind',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('language',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'ru'"))

    with op.batch_alter_table('plantation_beds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status_effect',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index('idx_inventory_rarity')
        batch_op.drop_index('idx_inventory_player')
        batch_op.drop_index('idx_inventory_drink')

    with op.batch_alter_table('group_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_chats_notify_disabled'))
        batch_op.drop_index(batch_op.f('ix_group_chats_auto_delete_enabled'))

    with op.batch_alter_table('fertilizers', schema=None) as batch_op:
        batch_op.alter_column('effect_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('energy_drinks', schema=None) as batch_op:
        batch_op.alter_column('is_plantation',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    op.create_table('_alembic_tmp_energy_drinks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('image_path', sa.VARCHAR(), nullable=True),
    sa.Column('is_special', sa.BOOLEAN(), nullable=True),
    sa.Column('is_plantation', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('plantation_index', sa.INTEGER(), nullable=True),
    sa.Column('default_rarity', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
